Using timerlib from SmartLibs now :^)
git-svn-id: https://repo.cs.iastate.edu/svn/Smart/trunk@1486 a175ec86-2bff-0310-88ad-935c21b1773c

diff --git a/Config-funcs b/Config-funcs
--- a/Config-funcs
+++ b/Config-funcs
@@ -63,6 +63,24 @@ find_mddlib() {
 
 # ============================================================
 
+try_timerlib() {
+  if [ -f $1/include/timerlib.h ]; then
+    printf "TimerLib found at $1\n"
+    export TIMER_LIBRARY="$1"
+    return 0
+  fi
+  return 1
+}
+
+find_timerlib() {
+  try_timerlib $SMARTLIBS && return 0
+  try_timerlib $TIMER_LIBRARY && return 0
+  try_timerlib $HOME/SmartLibs/trunk && return 0
+  printf "Cannot find Timer Library\n"
+  printf "Set environment variable TIMER_LIBRARY\n"
+  return 1
+}
+
 # ============================================================
 
 try_simlib() {
@@ -222,6 +240,7 @@ findlibs() {
 # Look for Smart Libs
 #
 
+  find_timerlib || return 1
   find_simlib || return 1
   find_rnglib || return 1
   find_lslib || return 1
@@ -233,7 +252,7 @@ findlibs() {
 #
 # Build -I path list for Smart Libs, and exclude duplicates
 #
-  IncludePath=`echo "-I$SIM_LIBRARY/include -I$RNG_LIBRARY/include -I$LS_LIBRARY/include -I$STATE_LIBRARY/include -I$GRAPH_LIBRARY/include -I$MC_LIBRARY/include -I$IS_LIBRARY/include" | xargs -n 1 | sort -u | xargs`
+  IncludePath=`echo "-I$TIMER_LIBRARY/include -I$SIM_LIBRARY/include -I$RNG_LIBRARY/include -I$LS_LIBRARY/include -I$STATE_LIBRARY/include -I$GRAPH_LIBRARY/include -I$MC_LIBRARY/include -I$IS_LIBRARY/include" | xargs -n 1 | sort -u | xargs`
   
   CPPFLAGS="$IncludePath $CPPFLAGS"
 
