New regression tests, platform determined automagically
git-svn-id: https://repo.cs.iastate.edu/svn/Smart/trunk@1502 a175ec86-2bff-0310-88ad-935c21b1773c

diff --git a/Tests/TestAny b/Tests/TestAny
--- a/Tests/TestAny
+++ b/Tests/TestAny
@@ -10,22 +10,36 @@
 #
 
 if [ $# -lt 1 ]; then
-  echo "Usage: $0 <exec_dir> test1 test2 ..."
+  echo "Usage: $0 <exec_dir> <src_dir> test1 test2 ..."
   echo "Runs appropriate executable on each test file and compares with saved output."
   exit
 fi
 
+MACHINE=`gcc -dumpmachine`
+
 sm_okcount="0"
+sm_blcount="0"
 sm_chcount="0"
 sm_fcount="0"
 icp_okcount="0"
+icp_blcount="0"
 icp_chcount="0"
 icp_fcount="0"
 outfile=`mktemp test.XXXXXXXX`
 
 OK=" [1;32m   OK   [0;39m"
+BAIL=" [1;33m  MISS  [0;39m"
 CHANGE=" [1;33m CHANGE [0;39m"
 FAILED=" [1;31m FAILED [0;39m"
+
+# Terminate cleanly on ctrl-C
+ctrl_c() {
+  printf "\n\nCaught CTRL-C, bailing out\n\n"
+  rm $outfile
+  exit 1
+}
+
+trap ctrl_c INT
 
 #
 #
@@ -37,6 +51,23 @@ MakeRedirectString()
   printf "cond(%s_file(%c%s%c), null, exit(1));" $1 '"' $outfile '"'
 }
 
+#
+#
+# Helper function: find best output file to test against
+# Argument 1: input filename
+#
+FindOutputFile()
+{
+  sufx="t.$MACHINE"
+  while [ "$sufx" ]; do
+    if [ -f $1.ou$sufx ]; then
+      echo $1.ou$sufx
+      return
+    fi
+    sufx=`sed 's/\(.*\)./\1/' <<< $sufx`
+  done
+  echo ""
+}
 
 SM_REDIRECT=`MakeRedirectString "error"; MakeRedirectString "warning"; MakeRedirectString "output"`
 
@@ -47,6 +78,17 @@ SM_REDIRECT=`MakeRedirectString "error"; MakeRedirectString "warning"; MakeRedir
 ProcessOK()
 {
   printf "$OK\n"
+  rm -f $TESTDIR/$1.diffs
+  rm -f $TESTDIR/$1.test
+}
+
+#
+# Helper function: Process "BAIL"
+#	Argument 1: test file
+#
+ProcessBAIL()
+{
+  printf "$BAIL\n\tNo match for $1.out.$MACHINE\n"
   rm -f $TESTDIR/$1.diffs
   rm -f $TESTDIR/$1.test
 }
@@ -90,17 +132,18 @@ TestSmart()
   rm -f $outfile
   if echo $SM_REDIRECT | $current/$SMART - $b; then
     # Run was successful.
-    if [ -f $b.out.$SMART_PLATFORM ]; then
-      cmpfile="$b.out.$SMART_PLATFORM"
+    cmpfile=`FindOutputFile $b`
+    if [ "$cmpfile" ]; then
+      if diff -b $cmpfile $outfile > $TESTDIR/$b.diffs; then
+        ProcessOK $b
+        sm_okcount=$[ $sm_okcount + 1 ]
+      else
+        ProcessChange $b
+        sm_chcount=$[ $sm_chcount + 1 ]
+      fi
     else
-      cmpfile="$b.out"
-    fi
-    if diff -b $cmpfile $outfile > $TESTDIR/$b.diffs; then
-      ProcessOK $b
-      sm_okcount=$[ $sm_okcount + 1 ]
-    else
-      ProcessChange $b
-      sm_chcount=$[ $sm_chcount + 1 ]
+      ProcessBAIL $b
+      sm_blcount=$[ $sm_blcount + 1 ]
     fi
   else
     # Run failed
@@ -129,17 +172,18 @@ TestICP()
   rm -f $outfile
   if $current/$ICP $b > $outfile; then
     # Run was successful.
-    if [ -f $b.out.$SMART_PLATFORM ]; then
-      cmpfile="$b.out.$SMART_PLATFORM"
+    cmpfile=`FindOutputFile $b`
+    if [ $cmpfile ]; then
+      if diff -b $cmpfile $outfile > $TESTDIR/$b.diffs; then
+        ProcessOK $b
+        icp_okcount=$[ $icp_okcount + 1 ]
+      else
+        ProcessChange $b
+        icp_chcount=$[ $icp_chcount + 1 ]
+      fi
     else
-      cmpfile="$b.out"
-    fi
-    if diff -b $cmpfile $outfile > $TESTDIR/$b.diffs; then
-      ProcessOK $b
-      icp_okcount=$[ $icp_okcount + 1 ]
-    else
-      ProcessChange $b
-      icp_chcount=$[ $icp_chcount + 1 ]
+      ProcessBAIL $b
+      icp_blcount=$[ $icp_blcount + 1 ]
     fi
   else
     # Run failed
@@ -153,8 +197,9 @@ TestICP()
 # Helper function: print summary for a given tool
 #	Argument 1: tool name
 #	Argument 2: count of "OKs"
-#	Argument 3: count of "CHANGEs"
-#	Argument 4: count of "FAILEDs"
+#	Argument 3: count of "BAILs"
+#	Argument 4: count of "CHANGEs"
+#	Argument 5: count of "FAILEDs"
 #
 PrintSummary()
 {
@@ -167,10 +212,13 @@ PrintSummary()
     printf "  $OK: %3d\n" $2
   fi
   if [ "$3" -gt 0 ]; then
-    printf "  $CHANGE: %3d\n" $3
+    printf "  $BAIL: %3d\n" $3
   fi
   if [ "$4" -gt 0 ]; then
-    printf "  $FAILED: %3d\n" $4
+    printf "  $CHANGE: %3d\n" $4
+  fi
+  if [ "$4" -gt 0 ]; then
+    printf "  $FAILED: %3d\n" $5
   fi
 }
 
@@ -208,8 +256,8 @@ do
 done
 printf "  %-40s    ======\n" "========================="
 
-PrintSummary `basename $SMART` $sm_okcount $sm_chcount $sm_fcount
-PrintSummary `basename $ICP` $icp_okcount $icp_chcount $icp_fcount
+PrintSummary `basename $SMART` $sm_okcount $sm_blcount $sm_chcount $sm_fcount
+PrintSummary `basename $ICP` $icp_okcount $icp_blcount $icp_chcount $icp_fcount
 
 rm -f $outfile
 
